//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for BookingStatus.
const (
	Active    BookingStatus = "active"
	Cancelled BookingStatus = "cancelled"
)

// Valid indicates whether the value is a known member of the BookingStatus enum.
func (e BookingStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Cancelled:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseErrorCode.
const (
	BOOKINGNOTFOUND   ErrorResponseErrorCode = "BOOKING_NOT_FOUND"
	FORBIDDEN         ErrorResponseErrorCode = "FORBIDDEN"
	INTERNALERROR     ErrorResponseErrorCode = "INTERNAL_ERROR"
	INVALIDREQUEST    ErrorResponseErrorCode = "INVALID_REQUEST"
	NOTFOUND          ErrorResponseErrorCode = "NOT_FOUND"
	ROOMNOTFOUND      ErrorResponseErrorCode = "ROOM_NOT_FOUND"
	SCHEDULEEXISTS    ErrorResponseErrorCode = "SCHEDULE_EXISTS"
	SLOTALREADYBOOKED ErrorResponseErrorCode = "SLOT_ALREADY_BOOKED"
	SLOTNOTFOUND      ErrorResponseErrorCode = "SLOT_NOT_FOUND"
	UNAUTHORIZED      ErrorResponseErrorCode = "UNAUTHORIZED"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case BOOKINGNOTFOUND:
		return true
	case FORBIDDEN:
		return true
	case INTERNALERROR:
		return true
	case INVALIDREQUEST:
		return true
	case NOTFOUND:
		return true
	case ROOMNOTFOUND:
		return true
	case SCHEDULEEXISTS:
		return true
	case SLOTALREADYBOOKED:
		return true
	case SLOTNOTFOUND:
		return true
	case UNAUTHORIZED:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for PostDummyLoginJSONBodyRole.
const (
	PostDummyLoginJSONBodyRoleAdmin PostDummyLoginJSONBodyRole = "admin"
	PostDummyLoginJSONBodyRoleUser  PostDummyLoginJSONBodyRole = "user"
)

// Valid indicates whether the value is a known member of the PostDummyLoginJSONBodyRole enum.
func (e PostDummyLoginJSONBodyRole) Valid() bool {
	switch e {
	case PostDummyLoginJSONBodyRoleAdmin:
		return true
	case PostDummyLoginJSONBodyRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for PostRegisterJSONBodyRole.
const (
	PostRegisterJSONBodyRoleAdmin PostRegisterJSONBodyRole = "admin"
	PostRegisterJSONBodyRoleUser  PostRegisterJSONBodyRole = "user"
)

// Valid indicates whether the value is a known member of the PostRegisterJSONBodyRole enum.
func (e PostRegisterJSONBodyRole) Valid() bool {
	switch e {
	case PostRegisterJSONBodyRoleAdmin:
		return true
	case PostRegisterJSONBodyRoleUser:
		return true
	default:
		return false
	}
}

// Booking defines model for Booking.
type Booking struct {
	ConferenceLink *string            `json:"conferenceLink,omitempty"`
	CreatedAt      *time.Time         `json:"createdAt,omitempty"`
	Id             openapi_types.UUID `json:"id"`
	SlotId         openapi_types.UUID `json:"slotId"`
	Status         BookingStatus      `json:"status"`
	UserId         openapi_types.UUID `json:"userId"`
}

// BookingStatus defines model for Booking.Status.
type BookingStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// InternalErrorResponse defines model for InternalErrorResponse.
type InternalErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// Page Текущая страница (начиная с 1)
	Page int `json:"page"`

	// PageSize Размер страницы
	PageSize int `json:"pageSize"`

	// Total Общее количество записей
	Total int `json:"total"`
}

// Room defines model for Room.
type Room struct {
	Capacity    *int               `json:"capacity,omitempty"`
	CreatedAt   *time.Time         `json:"createdAt,omitempty"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	// DaysOfWeek 1=Пн .. 7=Вс, дни доступности. Каждое значение должно быть в диапазоне 1–7.
	DaysOfWeek []int `json:"daysOfWeek"`

	// EndTime Время окончания (HH:MM) в рамках дня. Интерпретируется как UTC.
	EndTime string              `json:"endTime"`
	Id      *openapi_types.UUID `json:"id,omitempty"`
	RoomId  openapi_types.UUID  `json:"roomId"`

	// StartTime Время начала (HH:MM) в рамках дня. Интерпретируется как UTC.
	StartTime string `json:"startTime"`
}

// Slot defines model for Slot.
type Slot struct {
	// End Время окончания слота в UTC (ISO 8601, например 2024-06-10T09:30:00Z)
	End    time.Time          `json:"end"`
	Id     openapi_types.UUID `json:"id"`
	RoomId openapi_types.UUID `json:"roomId"`

	// Start Время начала слота в UTC (ISO 8601, например 2024-06-10T09:00:00Z)
	Start time.Time `json:"start"`
}

// Token defines model for Token.
type Token struct {
	// Token JWT для заголовка Authorization Bearer
	Token string `json:"token"`
}

// User defines model for User.
type User struct {
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Role      UserRole            `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// BookingIdPath defines model for BookingIdPath.
type BookingIdPath = openapi_types.UUID

// RoomIdPath defines model for RoomIdPath.
type RoomIdPath = openapi_types.UUID

// PostBookingsCreateJSONBody defines parameters for PostBookingsCreate.
type PostBookingsCreateJSONBody struct {
	CreateConferenceLink *bool              `json:"createConferenceLink,omitempty"`
	SlotId               openapi_types.UUID `json:"slotId"`
}

// GetBookingsListParams defines parameters for GetBookingsList.
type GetBookingsListParams struct {
	// Page Номер страницы (начиная с 1). По умолчанию 1.
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Количество записей на странице. По умолчанию 20, максимум 100.
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostDummyLoginJSONBody defines parameters for PostDummyLogin.
type PostDummyLoginJSONBody struct {
	Role PostDummyLoginJSONBodyRole `json:"role"`
}

// PostDummyLoginJSONBodyRole defines parameters for PostDummyLogin.
type PostDummyLoginJSONBodyRole string

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// PostRegisterJSONBody defines parameters for PostRegister.
type PostRegisterJSONBody struct {
	Email    openapi_types.Email      `json:"email"`
	Password string                   `json:"password"`
	Role     PostRegisterJSONBodyRole `json:"role"`
}

// PostRegisterJSONBodyRole defines parameters for PostRegister.
type PostRegisterJSONBodyRole string

// PostRoomsCreateJSONBody defines parameters for PostRoomsCreate.
type PostRoomsCreateJSONBody struct {
	Capacity    *int    `json:"capacity,omitempty"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// GetRoomsRoomIdSlotsListParams defines parameters for GetRoomsRoomIdSlotsList.
type GetRoomsRoomIdSlotsListParams struct {
	// Date Дата в формате ISO 8601 (например: 2024-06-10). Обязательный параметр; при отсутствии — 400.
	Date openapi_types.Date `form:"date" json:"date"`
}

// PostBookingsCreateJSONRequestBody defines body for PostBookingsCreate for application/json ContentType.
type PostBookingsCreateJSONRequestBody PostBookingsCreateJSONBody

// PostDummyLoginJSONRequestBody defines body for PostDummyLogin for application/json ContentType.
type PostDummyLoginJSONRequestBody PostDummyLoginJSONBody

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody PostRegisterJSONBody

// PostRoomsCreateJSONRequestBody defines body for PostRoomsCreate for application/json ContentType.
type PostRoomsCreateJSONRequestBody PostRoomsCreateJSONBody

// PostRoomsRoomIdScheduleCreateJSONRequestBody defines body for PostRoomsRoomIdScheduleCreate for application/json ContentType.
type PostRoomsRoomIdScheduleCreateJSONRequestBody = Schedule

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать бронь на слот (только user). Опционально — запросить ссылку на конференцию.
	// (POST /bookings/create)
	PostBookingsCreate(w http.ResponseWriter, r *http.Request)
	// Список всех броней с пагинацией (только admin)
	// (GET /bookings/list)
	GetBookingsList(w http.ResponseWriter, r *http.Request, params GetBookingsListParams)
	// Список броней текущего пользователя (только user)
	// (GET /bookings/my)
	GetBookingsMy(w http.ResponseWriter, r *http.Request)
	// Отменить бронь (только своя бронь, только user)
	// (POST /bookings/{bookingId}/cancel)
	PostBookingsBookingIdCancel(w http.ResponseWriter, r *http.Request, bookingId BookingIdPath)
	// Получить тестовый JWT по роли (ОБЯЗАТЕЛЬНО). Доступен без авторизации.
	// (POST /dummyLogin)
	PostDummyLogin(w http.ResponseWriter, r *http.Request)
	// Авторизация по email и паролю (ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ — необязательно)
	// (POST /login)
	PostLogin(w http.ResponseWriter, r *http.Request)
	// Регистрация пользователя (ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ — необязательно)
	// (POST /register)
	PostRegister(w http.ResponseWriter, r *http.Request)
	// Создать переговорку (только admin)
	// (POST /rooms/create)
	PostRoomsCreate(w http.ResponseWriter, r *http.Request)
	// Список переговорок (admin и user)
	// (GET /rooms/list)
	GetRoomsList(w http.ResponseWriter, r *http.Request)
	// Создать расписание переговорки (только admin, только один раз). Длительность слота 30 мин. После создания расписание изменить нельзя.
	// (POST /rooms/{roomId}/schedule/create)
	PostRoomsRoomIdScheduleCreate(w http.ResponseWriter, r *http.Request, roomId RoomIdPath)
	// Список доступных для бронирования слотов по переговорке и дате (admin и user). Наиболее нагруженный эндпоинт.
	// (GET /rooms/{roomId}/slots/list)
	GetRoomsRoomIdSlotsList(w http.ResponseWriter, r *http.Request, roomId RoomIdPath, params GetRoomsRoomIdSlotsListParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostBookingsCreate operation middleware
func (siw *ServerInterfaceWrapper) PostBookingsCreate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostBookingsCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBookingsList operation middleware
func (siw *ServerInterfaceWrapper) GetBookingsList(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBookingsListParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBookingsList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBookingsMy operation middleware
func (siw *ServerInterfaceWrapper) GetBookingsMy(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBookingsMy(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostBookingsBookingIdCancel operation middleware
func (siw *ServerInterfaceWrapper) PostBookingsBookingIdCancel(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "bookingId" -------------
	var bookingId BookingIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "bookingId", r.PathValue("bookingId"), &bookingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "bookingId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostBookingsBookingIdCancel(w, r, bookingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDummyLogin operation middleware
func (siw *ServerInterfaceWrapper) PostDummyLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDummyLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRegister operation middleware
func (siw *ServerInterfaceWrapper) PostRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRoomsCreate operation middleware
func (siw *ServerInterfaceWrapper) PostRoomsCreate(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRoomsCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoomsList operation middleware
func (siw *ServerInterfaceWrapper) GetRoomsList(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomsList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRoomsRoomIdScheduleCreate operation middleware
func (siw *ServerInterfaceWrapper) PostRoomsRoomIdScheduleCreate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId RoomIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRoomsRoomIdScheduleCreate(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoomsRoomIdSlotsList operation middleware
func (siw *ServerInterfaceWrapper) GetRoomsRoomIdSlotsList(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId RoomIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRoomsRoomIdSlotsListParams

	// ------------- Required query parameter "date" -------------

	if paramValue := r.URL.Query().Get("date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomsRoomIdSlotsList(w, r, roomId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/bookings/create", wrapper.PostBookingsCreate)
	m.HandleFunc("GET "+options.BaseURL+"/bookings/list", wrapper.GetBookingsList)
	m.HandleFunc("GET "+options.BaseURL+"/bookings/my", wrapper.GetBookingsMy)
	m.HandleFunc("POST "+options.BaseURL+"/bookings/{bookingId}/cancel", wrapper.PostBookingsBookingIdCancel)
	m.HandleFunc("POST "+options.BaseURL+"/dummyLogin", wrapper.PostDummyLogin)
	m.HandleFunc("POST "+options.BaseURL+"/login", wrapper.PostLogin)
	m.HandleFunc("POST "+options.BaseURL+"/register", wrapper.PostRegister)
	m.HandleFunc("POST "+options.BaseURL+"/rooms/create", wrapper.PostRoomsCreate)
	m.HandleFunc("GET "+options.BaseURL+"/rooms/list", wrapper.GetRoomsList)
	m.HandleFunc("POST "+options.BaseURL+"/rooms/{roomId}/schedule/create", wrapper.PostRoomsRoomIdScheduleCreate)
	m.HandleFunc("GET "+options.BaseURL+"/rooms/{roomId}/slots/list", wrapper.GetRoomsRoomIdSlotsList)

	return m
}
